version: '3'

services:
  mongodb: 
    image: mongo:5.0.0
    container_name: mongodb
    restart: always
    ports:
      - 6000:27017
    volumes:
      - ./mongo:/data/db

  mysql:
    image: mysql:8.0.22
    platform: linux/x86_64
    container_name: mysql
    environment:
      MYSQL_DATABASE: musicDB
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    restart: always

  php:
    build:
      context: ./docker/php
      args:
        php_version: 8.0-apache
    container_name: php
    ports:
      - "81:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql

  phpmyadmin-witworks:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on: 
      - mysql
    ports: 
      - "82:80"
    links: 
      - mysql:db